### ISSUE TITLE
bug in doComchap (src/usr/local/bin/plexprocess)

### ISSUE THREAD

**Issue by christianuhlmann** [mjbrowns/plexpost#10]
Hello,

I found a bug in doComchap.
check at the beginning:
`if [ -f "${WF1%.*}.edl" ] ; then`
thats wrong and need to be negating with !

in doComcut this is implemented correctly
` if [ ! -f "${WF1%.*}.edl" ]; then`

see correspondig pull request https://github.com/mjbrowns/plexpost/pull/8

**Comment by mjbrowns** [comment]
Yep.  Good catch.  Merged.
