### ISSUE TITLE
Execution complaining about syntax error

### ISSUE THREAD

**Issue by simora** [mjbrowns/plexpost#6]
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (plexprocess) - Starting 
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (prepComskip) - Using comskip ini file /config/comskip.ini
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (doComskip) - Starting Commercial detection
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (doComskip) - Commercials were detected
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (doComcut) - Starting Commercial Cutting
c717682c45d393eee3a01618c3e22faa3c11702b - INFO: (doTranscode) - Starting Transcode (using plexprocess-transcode)
stat: cannot stat '/postdata/queue/working-c717682c45d393eee3a01618c3e22faa3c11702b/transcoded.mkv': No such file or directory
/usr/local/bin/plexprocess: line 110: 665423659/5 > : syntax error: operand expected (error token is "> ")
c717682c45d393eee3a01618c3e22faa3c11702b - ERROR: (doFinalMove) Transcoded output file not found! (/postdata/queue/working-c717682c45d393eee3a01618c3e22faa3c11702b/transcoded.mkv)

**Comment by simora** [comment]
More log info

comskip.log

The commandline used was:
comskip -q -n --ini=/postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comskip.ini /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/original.mkv

Setting ini file to /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comskip.ini as per commandline
Using /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comskip.ini for initiation values.
Commercials were found.

transcode.log

[05:16:23] hb_init: starting libhb thread
[05:16:23] thread 2b5fd3b65700 started ("libhb")
HandBrake 1.0.4 (2017040900) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comproc.mkv...
[05:16:23] CPU: 
[05:16:23]  - logical processor count: 8
[05:16:23] hb_scan: path=/postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comproc.mkv, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:274: failed opening UDF image /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comproc.mkv
disc.c:352: error opening file BDMV/index.bdmv
disc.c:352: error opening file BDMV/BACKUP/index.bdmv
[05:16:23] bd: not a bd - trying as a stream/file instead
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.BUP.
[05:16:23] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from '/postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comproc.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:20:38.58, start: 0.000000, bitrate: N/A
    Chapter #0:0: start 15.850000, end 320.190000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 320.190000, end 971.470000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 971.469000, end 1254.639000
    Metadata:
      title           : Chapter 3
    Stream #0:0: Video: h264 (High)
      yuv420p, tv, bt709/bt709/bt709
      1920x1080 [PAR 1:1 DAR 16:9], PAR 1:1 DAR 16:9
      29.97 fps, 1k tbn (default)
    Metadata:
      DURATION        : 00:20:38.588000000
    Stream #0:1: Audio: ac3
      48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      DURATION        : 00:20:38.560000000
[05:16:23] scan: decoding previews for title 1

Scanning title 1 of 1, preview 1, 0.00 %[05:16:23] scan: audio 0x1: ac3, rate=48000Hz, bitrate=192000 Unknown (AC3) (2.0 ch)

Scanning title 1 of 1, preview 2, 20.00 %
Scanning title 1 of 1, preview 4, 40.00 %
Scanning title 1 of 1, preview 6, 60.00 %
Scanning title 1 of 1, preview 8, 80.00 %
Scanning title 1 of 1, preview 10, 100.00 %[05:16:24] scan: 10 previews, 1920x1080, 29.970 fps, autocrop = 0/0/0/4, aspect 16:9, PAR 1:1
[05:16:24] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: /postdata/queue/working-eb429fc044c23854c6d05d267071448621cd099a/comproc.mkv
  + duration: 00:20:38
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 29.970 fps
  + autocrop: 0/0/0/4
  + support opencl: no
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:05:20
    + 2: cells 0->0, 0 blocks, duration 00:10:51
    + 3: cells 0->0, 0 blocks, duration 00:04:43
  + audio tracks:
    + 1, Unknown (AC3) (2.0 ch) (iso639-2: und), 48000Hz, 192000bps
  + subtitle tracks:
    + 1, Closed Captions (iso639-2: und) (Text)(CC)
HandBrake has exited.

**Comment by mjbrowns** [comment]
So.  I've seen this and I really can't do anything about it that I know of.  In this case, handbrake is suddenly exiting without doing anything and without reporting an error code.

Believe it or not, in most case she I've seen, rerunning the job works.  

Best I can do is add some error handling for the case where HB generates no output.

**Comment by mjbrowns** [comment]
Error handling updated included in commit #911f221

Technically this is untested until someone runs into the scenario.
