### ISSUE TITLE
failed to run plexpost

### ISSUE THREAD

**Issue by christianuhlmann** [mjbrowns/plexpost#7]
hi,

i am clone the git repo and try to build the docker.
when i am starting the composer i get the following error:

```
sudo docker-compose up -d
Starting plexpost
Starting plextest

ERROR: for plexpost  Cannot start service plexpost: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/init\": stat /init: no such file or directory"
ERROR: Encountered errors while bringing up the project.
```
Can you tell me where the mistake is?

**Comment by mjbrowns** [comment]
It looks to me like you did not follow the instructions in BUILD.md -amely, did you actually run make? There are quite a few elements that have to be separately built at this point, so docker-compose doesn't do everything you need.  It also seems that you may not have properly customized the docker-compose values.

That said, unless you are trying to customize this project, you would be better off just using the container I've already created and published on [Dockerhub](https://hub.docker.com/r/mbrown/plexpost/).

**Comment by christianuhlmann** [comment]
Thanks a lot, I skipped the make command. sorry.
otherwise many thanks for the good work, I use plexpost of you very much.
but would like to set myself a bit with optimizations apart, maybe there will be a pull request from me soon :)
